name: Backend Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...

    - name: Build Docker image
      run: docker build -f docker/Dockerfile -t transport-booking-backend:${{ github.sha }} .

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker tag transport-booking-backend:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/transport-booking-backend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/transport-booking-backend:latest

    # Add deployment steps for your chosen platform (Railway, Render, etc.)
    # Example for Railway:
    - name: Deploy to Railway
      if: success()
      run: |
        # Install Railway CLI
        curl -fsSL https://railway.app/install.sh | sh
        # Deploy using Railway CLI or API
        # railway deploy --service transport-booking-backend

    # Alternative: Deploy to Render
    # - name: Deploy to Render
    #   run: |
    #     curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}